version: '3'
services:
  database:
    build:
      context: ./database
    ports:
      - "8000:8000"
    expose:
      - "8000"
  server:
    build: 
      context: ./server
    env_file:
      - ./server/.env
    ports:
     - "3000:3000"
    expose:
      - "3000"
    depends_on:
     - database
  client:
    build:
      context: ./client
    ports:
     - "80:8080"
    expose:
      - "80"
    depends_on:
     - server