services:
  - type: web
    name: studentifier-client
    env: docker
    rootDir: client
    region: frankfurt
    plan: free
  - type: web
    name: studentifier-sWerver
    env: docker
    rootDir: server
    region: frankfurt
    plan: free
  - type: web
    name: studentifier-database
    env: docker
    rootDir: database
    region: frankfurt
    plan: free